#pragma once

enum BUTTON_STATE { RELEASED, PRESSED };
enum BUTTON {
    BUTTON_UNKNOWN = 0,
    MOUSE_MOVED, MOUSE_MARGIN_LEFT, MOUSE_MARGIN_RIGHT, MOUSE_MARGIN_TOP, MOUSE_MARGIN_BOTTOM,
    MOUSE_LEFT, MOUSE_RIGHT, MOUSE_MIDDLE,
    MOUSE_SCROLL, MOUSE_SCROLL_SIDE,
    KEYBOARD_ESCAPE, KEYBOARD_ENTER, KEYBOARD_BACKSPACE, KEYBOARD_TAB, KEYBOARD_SPACE, KEYBOARD_LEFT, KEYBOARD_RIGHT, KEYBOARD_UP, KEYBOARD_DOWN,
    KEYBOARD_HOME, KEYBOARD_END, KEYBOARD_PAGEUP, KEYBOARD_PAGEDOWN, KEYBOARD_INSERT, KEYBOARD_DELETE,
    KEYBOARD_SHIFT, KEYBOARD_CTRL, KEYBOARD_ALT, KEYBOARD_SUPER,
    KEYBOARD_0, KEYBOARD_1, KEYBOARD_2, KEYBOARD_3, KEYBOARD_4, KEYBOARD_5, KEYBOARD_6, KEYBOARD_7, KEYBOARD_8, KEYBOARD_9,
    KEYBOARD_A, KEYBOARD_B, KEYBOARD_C, KEYBOARD_D, KEYBOARD_E, KEYBOARD_F, KEYBOARD_G, KEYBOARD_H, KEYBOARD_I, KEYBOARD_J, KEYBOARD_K, KEYBOARD_L, KEYBOARD_M, KEYBOARD_N, KEYBOARD_O,
    KEYBOARD_P, KEYBOARD_Q, KEYBOARD_R, KEYBOARD_S, KEYBOARD_T, KEYBOARD_U, KEYBOARD_V, KEYBOARD_W, KEYBOARD_X, KEYBOARD_Y, KEYBOARD_Z,
    KEYBOARD_F1, KEYBOARD_F2, KEYBOARD_F3, KEYBOARD_F4, KEYBOARD_F5, KEYBOARD_F6, KEYBOARD_F7, KEYBOARD_F8, KEYBOARD_F9, KEYBOARD_F10, KEYBOARD_F11, KEYBOARD_F12,
    BUTTON_COUNT
};
typedef void (*KEYBOARD_CB)(void*,enum BUTTON,enum BUTTON_STATE);
typedef void (*MOUSE_CB)(void*,int,int,enum BUTTON,int);
long long pf_ns_now(void);
#ifdef _WIN32
long long pf_ticks_to_ns(long long); // on Windows the ticks still need to be converted to ns
#endif
void pf_time_reset(void);
long long pf_ns_start(void);
void pf_timestamp(char*);
int pf_window_width();
int pf_window_height();
void *pf_surface_or_hwnd();
void *pf_display_or_instance();
int pf_window_visible();
int pf_poll_events();
void pf_create_window(char*,void*,KEYBOARD_CB,MOUSE_CB);
